/*
	このファイルは目的別に複数回includeされます。
	型定義として:	#define _E(type,name,args) typedef type (CALLBACK *name##_t) args;
	列挙として:		#define _E(type,name,args) _ent_##name,
	文字列として:	#define _E(type,name,args) #name,
 */

#if defined(MINIMUM_ENTRIES)

_E(LONG, SCardConnectA, (SCARDCONTEXT, LPCSTR, DWORD, DWORD, LPSCARDHANDLE, LPDWORD))
_E(LONG, SCardDisconnect, (SCARDHANDLE, DWORD))
_E(LONG, SCardEstablishContext, (DWORD, LPCVOID, LPCVOID, LPSCARDCONTEXT))
_E(LONG, SCardListReadersA, (SCARDCONTEXT, LPCSTR, LPSTR, LPDWORD))
_E(LONG, SCardReleaseContext, (SCARDCONTEXT))
_E(LONG, SCardTransmit, (SCARDHANDLE, LPCSCARD_IO_REQUEST, LPCBYTE, DWORD, LPSCARD_IO_REQUEST, LPBYTE, LPDWORD))

#else

_E(HANDLE, SCardAccessStartedEvent, (void))
_E(LONG, SCardCancel, (SCARDCONTEXT))
_E(LONG, SCardConnectA, (SCARDCONTEXT, LPCSTR, DWORD, DWORD, LPSCARDHANDLE, LPDWORD))
_E(LONG, SCardConnectW, (SCARDCONTEXT, LPCWSTR, DWORD, DWORD, LPSCARDHANDLE, LPDWORD))
_E(LONG, SCardDisconnect, (SCARDHANDLE, DWORD))
_E(LONG, SCardEstablishContext, (DWORD, LPCVOID, LPCVOID, LPSCARDCONTEXT))
_E(LONG, SCardFreeMemory, (SCARDCONTEXT, LPCVOID))
_E(LONG, SCardGetStatusChangeA, (SCARDCONTEXT, DWORD, LPSCARD_READERSTATEA, DWORD))
_E(LONG, SCardGetStatusChangeW, (SCARDCONTEXT, DWORD, LPSCARD_READERSTATEW, DWORD))
_E(LONG, SCardIsValidContext, (SCARDCONTEXT))
_E(LONG, SCardListReadersA, (SCARDCONTEXT, LPCSTR, LPSTR, LPDWORD))
_E(LONG, SCardListReadersW, (SCARDCONTEXT, LPCWSTR, LPWSTR, LPDWORD))
_E(LONG, SCardReconnect, (SCARDHANDLE, DWORD, DWORD, DWORD, LPDWORD))
_E(LONG, SCardReleaseContext, (SCARDCONTEXT))
_E(void, SCardReleaseStartedEvent, (void))
_E(LONG, SCardStatusA, (SCARDHANDLE, LPSTR, LPDWORD, LPDWORD, LPDWORD, LPBYTE, LPDWORD))
_E(LONG, SCardStatusW, (SCARDHANDLE, LPWSTR, LPDWORD, LPDWORD, LPDWORD, LPBYTE, LPDWORD))
_E(LONG, SCardTransmit, (SCARDHANDLE, LPCSCARD_IO_REQUEST, LPCBYTE, DWORD, LPSCARD_IO_REQUEST, LPBYTE, LPDWORD))

#endif

#if 0
_E(HANDLE, SCardAccessStartedEvent, (void))
_E(LONG, SCardAddReaderToGroupA, (SCARDCONTEXT, LPCSTR, LPCSTR))
_E(LONG, SCardAddReaderToGroupW, (SCARDCONTEXT, LPCWSTR, LPCWSTR))
_E(LONG, SCardBeginTransaction, (SCARDHANDLE))
_E(LONG, SCardCancel, (SCARDCONTEXT))
_E(LONG, SCardConnectA, (SCARDCONTEXT, LPCSTR, DWORD, DWORD, LPSCARDHANDLE, LPDWORD))
_E(LONG, SCardConnectW, (SCARDCONTEXT, LPCWSTR, DWORD, DWORD, LPSCARDHANDLE, LPDWORD))
_E(LONG, SCardControl, (SCARDHANDLE, DWORD, LPCVOID, DWORD, LPVOID, DWORD, LPDWORD))
_E(LONG, SCardDisconnect, (SCARDHANDLE, DWORD))
_E(LONG, SCardEndTransaction, (SCARDHANDLE, DWORD))
_E(LONG, SCardEstablishContext, (DWORD, LPCVOID, LPCVOID, LPSCARDCONTEXT))
_E(LONG, SCardForgetCardTypeA, (SCARDCONTEXT, LPCSTR))
_E(LONG, SCardForgetCardTypeW, (SCARDCONTEXT, LPCWSTR))
_E(LONG, SCardForgetReaderA, (SCARDCONTEXT, LPCSTR))
_E(LONG, SCardForgetReaderGroupA, (SCARDCONTEXT, LPCSTR))
_E(LONG, SCardForgetReaderGroupW, (SCARDCONTEXT, LPCWSTR))
_E(LONG, SCardForgetReaderW, (SCARDCONTEXT, LPCWSTR))
_E(LONG, SCardFreeMemory, (SCARDCONTEXT, LPCVOID))
_E(LONG, SCardGetAttrib, (SCARDHANDLE, DWORD, LPBYTE, LPDWORD))
_E(LONG, SCardGetCardTypeProviderNameA, (SCARDCONTEXT, LPCSTR, DWORD, LPSTR, LPDWORD))
_E(LONG, SCardGetCardTypeProviderNameW, (SCARDCONTEXT, LPCWSTR, DWORD, LPWSTR, LPDWORD))
_E(LONG, SCardGetProviderIdA, (SCARDCONTEXT, LPCSTR, LPGUID))
_E(LONG, SCardGetProviderIdW, (SCARDCONTEXT, LPCWSTR, LPGUID))
_E(LONG, SCardGetStatusChangeA, (SCARDCONTEXT, DWORD, LPSCARD_READERSTATEA, DWORD))
_E(LONG, SCardGetStatusChangeW, (SCARDCONTEXT, DWORD, LPSCARD_READERSTATEW, DWORD))
_E(LONG, SCardGetTransmitCount, (SCARDHANDLE, LPDWORD))
_E(LONG, SCardIntroduceCardTypeA, (SCARDCONTEXT, LPCSTR, LPCGUID, LPCGUID, DWORD, LPCBYTE, LPCBYTE, DWORD))
_E(LONG, SCardIntroduceCardTypeW, (SCARDCONTEXT, LPCWSTR, LPCGUID, LPCGUID, DWORD, LPCBYTE, LPCBYTE, DWORD))
_E(LONG, SCardIntroduceReaderA, (SCARDCONTEXT, LPCSTR, LPCSTR))
_E(LONG, SCardIntroduceReaderW, (SCARDCONTEXT, LPCWSTR, LPCWSTR))
_E(LONG, SCardIntroduceReaderGroupA, (SCARDCONTEXT, LPCSTR))
_E(LONG, SCardIntroduceReaderGroupW, (SCARDCONTEXT, LPCWSTR))
_E(LONG, SCardIsValidContext, (SCARDCONTEXT))
_E(LONG, SCardListCardsA, (SCARDCONTEXT, LPCBYTE, LPCGUID, DWORD, LPSTR, LPDWORD))
_E(LONG, SCardListCardsW, (SCARDCONTEXT, LPCBYTE, LPCGUID, DWORD, LPWSTR, LPDWORD))
_E(LONG, SCardListInterfacesA, (SCARDCONTEXT, LPCSTR, LPGUID, LPDWORD))
_E(LONG, SCardListInterfacesW, (SCARDCONTEXT, LPCWSTR, LPGUID, LPDWORD))
_E(LONG, SCardListReaderGroupsA, (SCARDCONTEXT, LPSTR, LPDWORD))
_E(LONG, SCardListReaderGroupsW, (SCARDCONTEXT, LPWSTR, LPDWORD))
_E(LONG, SCardListReadersA, (SCARDCONTEXT, LPCSTR, LPSTR, LPDWORD))
_E(LONG, SCardListReadersW, (SCARDCONTEXT, LPCWSTR, LPWSTR, LPDWORD))
_E(LONG, SCardLocateCardsA, (SCARDCONTEXT, LPCSTR, LPSCARD_READERSTATEA, DWORD))
_E(LONG, SCardLocateCardsW, (SCARDCONTEXT, LPCWSTR, LPSCARD_READERSTATEW, DWORD))
_E(LONG, SCardLocateCardsByATRA, (SCARDCONTEXT, LPSCARD_ATRMASK, DWORD, LPSCARD_READERSTATEA, DWORD))
_E(LONG, SCardLocateCardsByATRW, (SCARDCONTEXT, LPSCARD_ATRMASK, DWORD, LPSCARD_READERSTATEW, DWORD))
_E(LONG, SCardReadCacheA, (SCARDCONTEXT, UUID *, DWORD, LPSTR, PBYTE, DWORD *))
_E(LONG, SCardReadCacheW, (SCARDCONTEXT, UUID *, DWORD, LPWSTR, PBYTE, DWORD *))
_E(LONG, SCardReconnect, (SCARDHANDLE, DWORD, DWORD, DWORD, LPDWORD))
_E(LONG, SCardReleaseContext, (SCARDCONTEXT))
_E(void, SCardReleaseStartedEvent, (void))
_E(LONG, SCardRemoveReaderFromGroupA, (SCARDCONTEXT, LPCSTR, LPCSTR))
_E(LONG, SCardRemoveReaderFromGroupW, (SCARDCONTEXT, LPCWSTR, LPCWSTR))
_E(LONG, SCardSetAttrib, (SCARDHANDLE, DWORD, LPCBYTE, DWORD))
_E(LONG, SCardSetCardTypeProviderNameA, (SCARDCONTEXT, LPCSTR, DWORD, LPCSTR))
_E(LONG, SCardSetCardTypeProviderNameW, (SCARDCONTEXT, LPCWSTR, DWORD, LPCWSTR))
_E(LONG, SCardStatusA, (SCARDHANDLE, LPSTR, LPDWORD, LPDWORD, LPDWORD, LPBYTE, LPDWORD))
_E(LONG, SCardStatusW, (SCARDHANDLE, LPWSTR, LPDWORD, LPDWORD, LPDWORD, LPBYTE, LPDWORD))
_E(LONG, SCardTransmit, (SCARDHANDLE, LPCSCARD_IO_REQUEST, LPCBYTE, DWORD, LPSCARD_IO_REQUEST, LPBYTE, LPDWORD))
_E(LONG, SCardWriteCacheA, (SCARDCONTEXT, UUID *, DWORD, LPSTR, PBYTE, DWORD))
_E(LONG, SCardWriteCacheW, (SCARDCONTEXT, UUID *, DWORD, LPWSTR, PBYTE, DWORD))
#endif

/* 詳細不明エントリ (not documented) */
#if 0
_E(void, ClassInstall32, (void))
_E(HANDLE, SCardAccessNewReaderEvent, (void))
_E(LONG, SCardReleaseAllEvents, (void))
_E(LONG, SCardReleaseNewReaderEvent, (HANDLE))
_E(void, SCardState, (void))
#endif

/* 以下は関数エントリではありませんが、アドレス取得の簡単のため。 */
#if 0
_E(SCARD_IO_REQUEST, g_rgSCardRawPci, (void))
_E(SCARD_IO_REQUEST, g_rgSCardT0Pci, (void))
_E(SCARD_IO_REQUEST, g_rgSCardT1Pci, (void))
#endif
